---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: latest

inputs:
  - name: service-repo

outputs:
  - name: build-output

params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false

run:
  path: service-repo/ci/tasks/build-service/task.sh
