spring:
  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp
  profiles: default
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/tracker_db
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create
