---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: service-repo
  type: git
  source:
    uri: {{git-url}}
    branch: {{git-branch}}
    username: ((git-username))
    # please uncomment as applicable
#    password: ((git-passwd))
#    private_key: ((git-private-key))

- name: deploy-dev
  type: cf
  source:
    api:             {{pws-api}}
    username:        ((deploy-username))
    password:        ((deploy-password))
    skip_cert_check: true
    organization:    {{pws-organization}}
    space:           {{pws-space}}

jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: service-repo
    trigger: true
  - task: build-service
    privileged: true
    file: service-repo/ci/tasks/build-service/task.yml
#    on_failure:
#      put: slack-alert
#      params:
#        channels: ci-pipeline
#        text: |
#          The $BUILD_PIPELINE_NAME build failed!
#          https://cognizantdigital.slack.com/archives/ci-pipeline/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
#        username: jh-concourse-user
#        icon_url: http://downloadicons.net/sites/default/files/error-icons-44565.png

  - put: deploy-dev
    params:
      manifest: build-output/manifest.yml
      path: build-output/*.jar

#    on_failure:
#      put: slack-alert
#      params:
#        channels: ci-pipeline
#        text: |
#          The $BUILD_PIPELINE_NAME failed deployment to dev space.
#          https://cognizantdigital.slack.com/archives/ci-pipeline/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
#        username: jh-concourse-user
#        icon_url: http://downloadicons.net/sites/default/files/error-icons-44565.png
#    on_success:
#     put: slack-alert
#     params:
#       channels: ci-pipeline
#       text: |
#         The $BUILD_PIPELINE_NAME successfully deployed to dev space.
#         https://cognizantdigital.slack.com/archives/ci-pipeline/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
#       username: jh-concourse-user
#       icon_url: http://vignette2.wikia.nocookie.net/legouniverse/images/f/f5/Jay_render.PNG/revision/latest?cb=20120406164257
