server:
  port: 8762
  
spring:
  application:
    name: zuul-server
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: ${EUREKA_URI:http://localhost:8761/eureka}