#Server port
server:
  port: 8888
 
#Git repo location.
spring:
  cloud:
    config:
      server:
        git:
          uri: ${USERPROFILE}\\Desktop\\config-server-repo
 
#Disable security of the Management endpoint
management:
  security:
    enabled: false
