spring:
  application:
    name: spring-cloud-eureka-client-0
    
server:
  port: 0
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
      