server:
  port: 8888
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/APARTMENT_DB?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: password1$
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
